name: Denis

on:
  push:
    tags:
     - 'test-gcp-dev-35'
     - 'test-gcp-qa'

env:
  tag: ${{ github.ref }}
  key: ${{ secrets.KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Environment Variable
      run: |
        echo "a=$key" >> $GITHUB_ENV

    - name: Use the value
      run: |
        echo "${{ env.a }}"

