name: Denis

on:
  push:
    tags:
     - 'test-gcp-dev-45'
     - 'test-gcp-qa'

env:
  tag: ${{ github.ref }}
  key: ${{ secrets.KEY }}
  SECRETS_KEY: ${{secrets.KEY}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Environment Variable
      run: |
        echo 'a<<EOF' >> $GITHUB_ENV
        printenv SECRETS_KEY >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Use the value
      run: |
        echo "${{ env.a }}"

