name: Denis

on:
  push:
    tags:
     - 'release-plugin-[0-9]+.[0-9]+.[0-9]+*'

env:
  tag: ${{ github.ref }}
  key: ${{ secrets.KEY }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set ${{ github.ref }}
      run: |
        $version = "${{ github.ref }}".Substring(3)
        echo $version

