name: Denis

on:
  push:
    tags:
     - 'test-gcp-dev-20'
     - 'test-gcp-qa'

env:
  tag: ${{ github.ref }}
  den_dev: ${{ secrets.KEY }}
  den_qa: qavalue
  den_prod: sdlfdjf
  tanik: ${{ secrets.TANIK }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Some Name
      run: |
       prefix="den_$(echo $tag|cut -d\- -f3)"
       echo ${!prefix} >> pref.json
       base64 --decode pref.json > orig.json
       cat orig.json

