name: Denis

on:
  push:
    tags:
     - 'test-gcp-dev-27'
     - 'test-gcp-qa'

env:
  tag: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Environment Variable
      run: |
        echo "a=tanik" >> $GITHUB_ENV
        echo "key=${{ secrets.KEY }}" >> $GITHUB_ENV

    - name: Use the value
      run: |
        echo "${{ env.a }}"
        echo "${{ env.key }}"

