name: Denis

on:
  push:
    tags:
     - 'release-gcp-dev-[0-9]+.[0-9]+.[0-9]+*'

env:
  tag: ${{ github.ref }}
  key: ${{ secrets.KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set
      run: |
        tag=${{ github.ref }}
        first=$( echo $tag| cut -d'-' -f1)
        second=$( echo $tag| cut -d'-' -f2)
        len=$((${#first} + ${#second} + 2))
        version=${tag:$len}
        echo $version

